const DEFAULT_PAGE_INDEX = 1
const DEFAULT_PAGE_SIZE = 10
const DEFAULT_ROW_KEY = 'id'
const DEFAULT_EMPTY_VALUE = '-'

export { DEFAULT_PAGE_INDEX, DEFAULT_PAGE_SIZE, DEFAULT_ROW_KEY, DEFAULT_EMPTY_VALUE }
